import { ExamTemplateDefinition } from './types';

export const OFFICIAL_EXAM_TEMPLATES: Record<string, ExamTemplateDefinition> = {
  CAT: {
    id: 'cat_official',
    name: 'CAT (Common Admission Test)',
    shortName: 'CAT',
    examType: 'CAT',
    category: 'management',
    description: 'IIMs Standard: 3 strictly timed 40-minute sections (120 mins). No inter-sectional switching. Onscreen scientific calculator provided.',
    officialPatternYear: '2024-2025 Pattern',
    totalTimeMinutes: 120,
    totalQuestions: 66,
    totalMarks: 198,
    rules: {
      totalTimeMinutes: 120,
      timingMode: 'per_section_strict',
      isStrictSectionTimed: true,
      allowSectionSwitching: false,
      allowRevisiting: false,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: true,
      calculatorType: 'scientific_cat',
      hasQuestionPaperView: true,
      scoring: {
        mcqMarks: 3,
        mcqNegativeMarks: 1,
        titaMarks: 3,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    },
    sections: [
      {
        id: 'VARC',
        name: 'Verbal Ability & Reading Comprehension',
        shortCode: 'VARC',
        durationMinutes: 40,
        targetQuestions: 24,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'DILR',
        name: 'Data Interpretation & Logical Reasoning',
        shortCode: 'DILR',
        durationMinutes: 40,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'QA',
        name: 'Quantitative Ability',
        shortCode: 'QA',
        durationMinutes: 40,
        targetQuestions: 22,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 115) return 99.95;
      if (score >= 100) return 99.7;
      if (score >= 88) return 99.2;
      if (score >= 76) return 98.0;
      if (score >= 64) return 95.0;
      if (score >= 52) return 90.0;
      if (score >= 42) return 85.0;
      if (score >= 32) return 75.0;
      if (score >= 22) return 60.0;
      if (score >= 12) return 40.0;
      if (score > 0) return 25.0;
      return 5.0;
    },
  },

  XAT: {
    id: 'xat_official',
    name: 'XAT (Xavier Aptitude Test)',
    shortName: 'XAT',
    examType: 'XAT',
    category: 'management',
    description: 'XLRI Standard: Part 1 (VALR, Decision Making, QA-DI) with 175 min shared pool & free section switching. Negative marks for unattempted questions beyond 8 skips. No calculators.',
    officialPatternYear: '2025 Pattern',
    totalTimeMinutes: 210,
    totalQuestions: 95,
    totalMarks: 95,
    rules: {
      totalTimeMinutes: 210,
      timingMode: 'shared_pool',
      isStrictSectionTimed: false,
      allowSectionSwitching: true,
      allowRevisiting: true,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: false,
      calculatorType: 'none',
      hasQuestionPaperView: true,
      scoring: {
        mcqMarks: 1,
        mcqNegativeMarks: 0.25,
        titaMarks: 1,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0.10,
        unattemptedFreeLimit: 8,
      },
    },
    sections: [
      {
        id: 'VALR',
        name: 'Verbal Ability & Logical Reasoning',
        shortCode: 'VALR',
        durationMinutes: 60,
        targetQuestions: 26,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
        unattemptedPenalty: 0.10,
        unattemptedFreeLimit: 8,
      },
      {
        id: 'DM',
        name: 'Decision Making',
        shortCode: 'DM',
        durationMinutes: 50,
        targetQuestions: 21,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
        unattemptedPenalty: 0.10,
        unattemptedFreeLimit: 8,
      },
      {
        id: 'QADI',
        name: 'Quantitative Ability & Data Interpretation',
        shortCode: 'QA & DI',
        durationMinutes: 65,
        targetQuestions: 28,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
        unattemptedPenalty: 0.10,
        unattemptedFreeLimit: 8,
      },
      {
        id: 'GK',
        name: 'General Knowledge & Analytical Essay',
        shortCode: 'GK',
        durationMinutes: 30,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        marksPerCorrect: 1,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 48) return 99.8;
      if (score >= 42) return 99.0;
      if (score >= 36) return 97.0;
      if (score >= 30) return 92.0;
      if (score >= 25) return 85.0;
      if (score >= 20) return 75.0;
      if (score >= 15) return 60.0;
      if (score > 0) return 35.0;
      return 10.0;
    },
  },

  CMAT: {
    id: 'cmat_official',
    name: 'CMAT (Common Management Admission Test)',
    shortName: 'CMAT',
    examType: 'CMAT',
    category: 'management',
    description: 'NTA Standard: 5 sections with 20 questions each (100 Qs total in 180 min combined pool). +4 marks for correct, -1 for wrong.',
    officialPatternYear: '2025 Pattern',
    totalTimeMinutes: 180,
    totalQuestions: 100,
    totalMarks: 400,
    rules: {
      totalTimeMinutes: 180,
      timingMode: 'shared_pool',
      isStrictSectionTimed: false,
      allowSectionSwitching: true,
      allowRevisiting: true,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: false,
      calculatorType: 'none',
      hasQuestionPaperView: true,
      scoring: {
        mcqMarks: 4,
        mcqNegativeMarks: 1,
        titaMarks: 4,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    },
    sections: [
      {
        id: 'QT_DI',
        name: 'Quantitative Techniques & Data Interpretation',
        shortCode: 'QT-DI',
        durationMinutes: 36,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 4,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'LR',
        name: 'Logical Reasoning',
        shortCode: 'LR',
        durationMinutes: 36,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 4,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'LC',
        name: 'Language Comprehension',
        shortCode: 'LC',
        durationMinutes: 36,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 4,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'GA',
        name: 'General Awareness',
        shortCode: 'GA',
        durationMinutes: 36,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 4,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'IE',
        name: 'Innovation & Entrepreneurship',
        shortCode: 'IE',
        durationMinutes: 36,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 4,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 340) return 99.9;
      if (score >= 310) return 99.0;
      if (score >= 280) return 97.0;
      if (score >= 250) return 90.0;
      if (score >= 220) return 80.0;
      if (score >= 180) return 65.0;
      if (score > 0) return 40.0;
      return 10.0;
    },
  },

  SNAP: {
    id: 'snap_official',
    name: 'SNAP (Symbiosis National Aptitude Test)',
    shortName: 'SNAP',
    examType: 'SNAP',
    category: 'management',
    description: 'Symbiosis Speed Test: 60 questions in 60 minutes with free navigation. +1 for correct, -0.25 for incorrect.',
    officialPatternYear: '2024-2025 Pattern',
    totalTimeMinutes: 60,
    totalQuestions: 60,
    totalMarks: 60,
    rules: {
      totalTimeMinutes: 60,
      timingMode: 'shared_pool',
      isStrictSectionTimed: false,
      allowSectionSwitching: true,
      allowRevisiting: true,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: false,
      calculatorType: 'none',
      hasQuestionPaperView: true,
      scoring: {
        mcqMarks: 1,
        mcqNegativeMarks: 0.25,
        titaMarks: 1,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    },
    sections: [
      {
        id: 'GE',
        name: 'General English (Reading Comp & Verbal Ability)',
        shortCode: 'English',
        durationMinutes: 15,
        targetQuestions: 15,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
      },
      {
        id: 'ALR',
        name: 'Analytical & Logical Reasoning',
        shortCode: 'Reasoning',
        durationMinutes: 25,
        targetQuestions: 25,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
      },
      {
        id: 'QA_DI_DS',
        name: 'Quantitative, Data Interpretation & Data Sufficiency',
        shortCode: 'QA & DI',
        durationMinutes: 20,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0.25,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 46) return 99.5;
      if (score >= 42) return 98.0;
      if (score >= 38) return 95.0;
      if (score >= 34) return 90.0;
      if (score >= 28) return 80.0;
      if (score >= 22) return 65.0;
      if (score > 0) return 30.0;
      return 10.0;
    },
  },

  NMAT: {
    id: 'nmat_official',
    name: 'NMAT by GMAC',
    shortName: 'NMAT',
    examType: 'NMAT',
    category: 'management',
    description: 'GMAC Computer Adaptive Standard: 3 strictly timed sections (120 mins). No negative marking (+3/0). Cannot return to completed sections.',
    officialPatternYear: '2024 Pattern',
    totalTimeMinutes: 120,
    totalQuestions: 108,
    totalMarks: 324,
    rules: {
      totalTimeMinutes: 120,
      timingMode: 'per_section_strict',
      isStrictSectionTimed: true,
      allowSectionSwitching: false,
      allowRevisiting: false,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: false,
      calculatorType: 'none',
      hasQuestionPaperView: false,
      scoring: {
        mcqMarks: 3,
        mcqNegativeMarks: 0,
        titaMarks: 3,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    },
    sections: [
      {
        id: 'LS',
        name: 'Language Skills',
        shortCode: 'Language',
        durationMinutes: 28,
        targetQuestions: 36,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        marksPerCorrect: 3,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
      {
        id: 'QS',
        name: 'Quantitative Skills',
        shortCode: 'Quant',
        durationMinutes: 52,
        targetQuestions: 36,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        marksPerCorrect: 3,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
      {
        id: 'LR',
        name: 'Logical Reasoning',
        shortCode: 'Logic',
        durationMinutes: 40,
        targetQuestions: 36,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        marksPerCorrect: 3,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 250) return 99.5;
      if (score >= 235) return 98.0;
      if (score >= 220) return 95.0;
      if (score >= 200) return 88.0;
      if (score >= 180) return 75.0;
      if (score >= 150) return 60.0;
      if (score > 0) return 30.0;
      return 10.0;
    },
  },

  GMAT: {
    id: 'gmat_focus',
    name: 'GMAT (Focus Edition)',
    shortName: 'GMAT',
    examType: 'GMAT',
    category: 'international',
    description: 'Official GMAC Focus Edition: 3 sections of 45 min each (135 min). Onscreen calculator only in Data Insights.',
    officialPatternYear: 'Focus Edition Pattern',
    totalTimeMinutes: 135,
    totalQuestions: 64,
    totalMarks: 205,
    rules: {
      totalTimeMinutes: 135,
      timingMode: 'candidate_order_timed',
      isStrictSectionTimed: true,
      allowSectionSwitching: false,
      allowRevisiting: false,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: true,
      calculatorType: 'standard_4function',
      hasQuestionPaperView: false,
      scoring: {
        mcqMarks: 1,
        mcqNegativeMarks: 0,
        titaMarks: 1,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0.5,
        unattemptedFreeLimit: 0,
      },
    },
    sections: [
      {
        id: 'QR',
        name: 'Quantitative Reasoning',
        shortCode: 'Quant',
        durationMinutes: 45,
        targetQuestions: 21,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: false,
        marksPerCorrect: 1,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
      {
        id: 'VR',
        name: 'Verbal Reasoning',
        shortCode: 'Verbal',
        durationMinutes: 45,
        targetQuestions: 23,
        allowedQuestionTypes: ['MCQ'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: false,
        marksPerCorrect: 1,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
      {
        id: 'DI',
        name: 'Data Insights',
        shortCode: 'Data Insights',
        durationMinutes: 45,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: true,
        allowSectionSwitching: false,
        allowRevisiting: false,
        hasCalculator: true,
        marksPerCorrect: 1,
        negativeMarksMcq: 0,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number) => {
      if (score >= 705) return 99.0;
      if (score >= 655) return 93.0;
      if (score >= 615) return 80.0;
      if (score >= 565) return 58.0;
      if (score >= 505) return 30.0;
      return 10.0;
    },
  },

  CUSTOM: {
    id: 'custom_exam',
    name: 'Custom Exam / Coaching Institute Mock',
    shortName: 'Custom',
    examType: 'CUSTOM',
    category: 'custom',
    description: 'Fully customizable exam format. Configure custom section counts, sectional timing rules, and marking schemes.',
    officialPatternYear: 'User-Defined Configuration',
    totalTimeMinutes: 120,
    totalQuestions: 60,
    totalMarks: 180,
    rules: {
      totalTimeMinutes: 120,
      timingMode: 'shared_pool',
      isStrictSectionTimed: false,
      allowSectionSwitching: true,
      allowRevisiting: true,
      autoSubmitOnTimeout: true,
      allowEarlySectionSubmit: true,
      hasOnscreenCalculator: true,
      calculatorType: 'scientific_cat',
      hasQuestionPaperView: true,
      scoring: {
        mcqMarks: 3,
        mcqNegativeMarks: 1,
        titaMarks: 3,
        titaNegativeMarks: 0,
        unattemptedPenalty: 0,
        unattemptedFreeLimit: 999,
      },
    },
    sections: [
      {
        id: 'SEC_1',
        name: 'Section 1',
        shortCode: 'SEC 1',
        durationMinutes: 40,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'SEC_2',
        name: 'Section 2',
        shortCode: 'SEC 2',
        durationMinutes: 40,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
      {
        id: 'SEC_3',
        name: 'Section 3',
        shortCode: 'SEC 3',
        durationMinutes: 40,
        targetQuestions: 20,
        allowedQuestionTypes: ['MCQ', 'TITA'],
        isTimedStrictly: false,
        allowSectionSwitching: true,
        allowRevisiting: true,
        marksPerCorrect: 3,
        negativeMarksMcq: 1,
        negativeMarksTita: 0,
      },
    ],
    percentileEstimator: (score: number, maxScore: number) => {
      const pct = maxScore > 0 ? (score / maxScore) * 100 : 0;
      return Math.min(99.9, Math.max(5.0, Math.round(pct * 1.1 * 10) / 10));
    },
  },
};
