import React, { useState, useEffect } from 'react';
import { MockTest, UserAttempt, Question, MockSection } from './types';
import { StorageService } from './utils/storage';
import { SetupMockView } from './components/setup/SetupMockView';
import { ReadyScreen } from './components/exam/ReadyScreen';
import { HomeDashboard } from './components/dashboard/HomeDashboard';
import { ExamScreen } from './components/exam/ExamScreen';
import { AnalyticsDashboard } from './components/analytics/AnalyticsDashboard';
import { MistakeNotebook } from './components/mistakes/MistakeNotebook';
import { AiCoachView } from './components/coach/AiCoachView';

export type AppView = 'setup' | 'ready' | 'home' | 'exam' | 'analytics' | 'mistakes' | 'coach';

export default function App() {
  const [currentView, setCurrentView] = useState<AppView>('setup');
  const [activeMock, setActiveMock] = useState<MockTest | null>(null);
  const [activeAttempt, setActiveAttempt] = useState<UserAttempt | null>(null);
  const [previousView, setPreviousView] = useState<AppView>('setup');

  // Check if there was an active attempt in progress or initialize storage
  useEffect(() => {
    // Ensure preloaded mocks exist
    StorageService.getMocks();
  }, []);

  // Handler: Transition to Ready confirmation screen before starting exam
  const handleOpenReadyScreen = (mock: MockTest) => {
    setActiveMock(mock);
    setPreviousView(currentView);
    setCurrentView('ready');
  };

  // Handler: Launch exam from Ready screen
  const handleLaunchExam = () => {
    if (!activeMock) return;
    setActiveAttempt(null);
    setCurrentView('exam');
  };

  // Handler: Resume an in-progress auto-saved mock exam
  const handleResumeExam = (mock: MockTest, attempt: UserAttempt) => {
    setActiveMock(mock);
    setActiveAttempt(attempt);
    setCurrentView('exam');
  };

  // Handler: Exam completed
  const handleFinishExam = (attempt: UserAttempt) => {
    setActiveAttempt(attempt);
    // Find the mock
    const allMocks = StorageService.getMocks();
    const targetMock = allMocks.find((m) => m.id === attempt.mockId) || activeMock;
    if (targetMock) setActiveMock(targetMock);
    setCurrentView('analytics');
  };

  // Handler: View previous report
  const handleViewAttemptReport = (attempt: UserAttempt, mock: MockTest) => {
    setActiveAttempt(attempt);
    setActiveMock(mock);
    setCurrentView('analytics');
  };

  // Handler: Start practice with specific mistake questions
  const handleStartMistakePractice = (mistakeQuestions: Question[]) => {
    if (mistakeQuestions.length === 0) return;

    const customPracticeMock: MockTest = {
      id: `mistake_drill_${Date.now()}`,
      title: `Active Mistakes Recovery Drill (${mistakeQuestions.length} Questions)`,
      examTemplateId: 'cat_standard',
      examType: 'SECTIONAL',
      year: '2025',
      slot: 'Targeted Drill',
      description: 'Focused practice exam generated from your unmastered Mistake Notebook.',
      totalDurationMinutes: Math.max(15, Math.ceil(mistakeQuestions.length * 2.5)),
      sections: [
        {
          id: 'MISTAKES',
          name: 'Mistakes Precision Drill',
          durationMinutes: Math.max(15, Math.ceil(mistakeQuestions.length * 2.5)),
          questions: mistakeQuestions.map((q, idx) => ({
            ...q,
            questionNumber: idx + 1,
          })),
        },
      ],
      createdDate: new Date().toISOString().split('T')[0],
      isPreloaded: false,
    };

    setActiveMock(customPracticeMock);
    setPreviousView('mistakes');
    setCurrentView('ready');
  };

  // Handler: Start custom drill from AI Coach
  const handleStartCustomDrill = (topic: string, count: number) => {
    // Gather all questions from all mocks matching topic
    const allMocks = StorageService.getMocks();
    const matchingQuestions: Question[] = [];

    allMocks.forEach((m) => {
      m.sections.forEach((s) => {
        s.questions.forEach((q) => {
          if (
            q.topic.toLowerCase().includes(topic.toLowerCase()) ||
            topic.toLowerCase().includes(q.topic.toLowerCase()) ||
            q.sectionId.toLowerCase().includes(topic.toLowerCase())
          ) {
            matchingQuestions.push(q);
          }
        });
      });
    });

    const chosenQuestions = matchingQuestions.slice(0, count);
    if (chosenQuestions.length === 0) {
      allMocks[0]?.sections[0]?.questions.slice(0, count).forEach((q) => chosenQuestions.push(q));
    }

    const drillMock: MockTest = {
      id: `coach_drill_${Date.now()}`,
      title: `AI Coach Drill: ${topic} Sprint`,
      examTemplateId: 'cat_standard',
      examType: 'SECTIONAL',
      year: '2025',
      slot: 'Recommended Drill',
      description: `Targeted practice set generated by your AI Study Coach to strengthen ${topic}.`,
      totalDurationMinutes: Math.max(10, Math.ceil(chosenQuestions.length * 2)),
      sections: [
        {
          id: 'DRILL',
          name: `${topic} Focused Drill`,
          durationMinutes: Math.max(10, Math.ceil(chosenQuestions.length * 2)),
          questions: chosenQuestions.map((q, idx) => ({
            ...q,
            questionNumber: idx + 1,
          })),
        },
      ],
      createdDate: new Date().toISOString().split('T')[0],
      isPreloaded: false,
    };

    setActiveMock(drillMock);
    setPreviousView('coach');
    setCurrentView('ready');
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-900 selection:bg-indigo-600 selection:text-white font-sans antialiased">
      {/* 1. Setup / Create Mock Screen (Default First Screen) */}
      {currentView === 'setup' && (
        <SetupMockView
          onMockCreated={(newMock) => {
            setActiveMock(newMock);
            setPreviousView('setup');
            setCurrentView('ready');
          }}
          onNavigateToLibrary={() => setCurrentView('home')}
          onNavigateToMistakes={() => setCurrentView('mistakes')}
          onNavigateToCoach={() => setCurrentView('coach')}
        />
      )}

      {/* 2. Ready Screen / Pre-Exam Confirmation Briefing */}
      {currentView === 'ready' && activeMock && (
        <ReadyScreen
          mock={activeMock}
          onStartExam={handleLaunchExam}
          onBack={() => setCurrentView(previousView || 'setup')}
        />
      )}

      {/* 3. Mock Library & Past Attempts Dashboard */}
      {currentView === 'home' && (
        <HomeDashboard
          onStartExam={handleOpenReadyScreen}
          onResumeExam={handleResumeExam}
          onOpenPdfUpload={() => setCurrentView('setup')}
          onOpenMistakeNotebook={() => setCurrentView('mistakes')}
          onOpenAiCoach={() => setCurrentView('coach')}
          onViewAttemptReport={handleViewAttemptReport}
        />
      )}

      {/* 4. Full CBT Examination Screen */}
      {currentView === 'exam' && activeMock && (
        <ExamScreen
          mock={activeMock}
          existingAttempt={activeAttempt}
          onFinishExam={handleFinishExam}
          onExitWithoutSaving={() => setCurrentView('home')}
        />
      )}

      {/* 5. Deterministic Analytics & Score Report */}
      {currentView === 'analytics' && activeAttempt && activeMock && (
        <AnalyticsDashboard
          attempt={activeAttempt}
          mock={activeMock}
          onRetake={() => handleOpenReadyScreen(activeMock)}
          onOpenMistakeNotebook={() => setCurrentView('mistakes')}
          onOpenAiCoach={() => setCurrentView('coach')}
          onBackToHome={() => setCurrentView('home')}
        />
      )}

      {/* 6. Mistake Notebook */}
      {currentView === 'mistakes' && (
        <MistakeNotebook
          onStartMistakePractice={handleStartMistakePractice}
          onBackToHome={() => setCurrentView('home')}
        />
      )}

      {/* 7. AI Study Coach */}
      {currentView === 'coach' && (
        <AiCoachView
          onStartCustomDrill={handleStartCustomDrill}
          onBackToHome={() => setCurrentView('home')}
        />
      )}
    </div>
  );
}
